export interface OGActivity {
  district: number;
  subOG: number;
  currentTR: string;
  nextTR: string;
  nextActivity: string;
  startTime: string; // Format: "HH:MM"
}

export const day1Activities: OGActivity[] = [
  {
    district: 1,
    subOG: 1,
    currentTR: "TR1",
    nextTR: "ARC - TR10",
    nextActivity: "Shrinking Island",
    startTime: "10:15",
  },
  {
    district: 1,
    subOG: 1,
    currentTR: "ARC - TR10",
    nextTR: "ARC - TR9",
    nextActivity: "The Irrelevant Answer",
    startTime: "10:45",
  },
  {
    district: 1,
    subOG: 1,
    currentTR: "ARC - TR9",
    nextTR: "ARC - TR6",
    nextActivity: "Borderlight Battle",
    startTime: "11:15",
  },
  {
    district: 1,
    subOG: 1,
    currentTR: "Arc - TR6",
    nextTR: "None",
    nextActivity: "Tic Tac Toe",
    startTime: "11:45",
  },
  {
    district: 2,
    subOG: 1,
    currentTR: "TR2",
    nextTR: "TR1",
    nextActivity: "Eyes Wide Shut",
    startTime: "10:15",
  },
  {
    district: 2,
    subOG: 1,
    currentTR: "TR1",
    nextTR: "ARC - TR 10",
    nextActivity: "Shrinking Island",
    startTime: "10:45",
  },
  {
    district: 2,
    subOG: 1,
    currentTR: "ARC - TR10",
    nextTR: "ARC - TR 9",
    nextActivity: "The Irrelevant Answer",
    startTime: "11:15",
  },
  {
    district: 2,
    subOG: 1,
    currentTR: "Arc - TR9",
    nextTR: "None",
    nextActivity: "Borderlight Battle",
    startTime: "11:45",
  },
  {
    district: 3,
    subOG: 1,
    currentTR: "TR3",
    nextTR: "TR2",
    nextActivity: "Dizzy Directions",
    startTime: "10:15",
  },
  {
    district: 3,
    subOG: 1,
    currentTR: "TR2",
    nextTR: "TR1",
    nextActivity: "Eyes Wide Shut",
    startTime: "10:45",
  },
  {
    district: 3,
    subOG: 1,
    currentTR: "TR1",
    nextTR: "ARC - TR10",
    nextActivity: "Shrinking Island",
    startTime: "11:15",
  },
  {
    district: 3,
    subOG: 1,
    currentTR: "Arc - TR10",
    nextTR: "None",
    nextActivity: "The Irrelevant Answer",
    startTime: "11:45",
  },
  {
    district: 4,
    subOG: 1,
    currentTR: "TR4",
    nextTR: "TR3",
    nextActivity: "Read My Mind",
    startTime: "10:15",
  },
  {
    district: 4,
    subOG: 1,
    currentTR: "TR3",
    nextTR: "TR2",
    nextActivity: "Dizzy Directions",
    startTime: "10:45",
  },
  {
    district: 4,
    subOG: 1,
    currentTR: "TR2",
    nextTR: "TR1",
    nextActivity: "Eyes Wide Shut",
    startTime: "11:15",
  },
  {
    district: 4,
    subOG: 1,
    currentTR: "TR1",
    nextTR: "None",
    nextActivity: "Shrinking Island",
    startTime: "11:45",
  },
  {
    district: 5,
    subOG: 1,
    currentTR: "TR5",
    nextTR: "TR4",
    nextActivity: "Stack and Steady",
    startTime: "10:15",
  },
  {
    district: 5,
    subOG: 1,
    currentTR: "TR4",
    nextTR: "TR3",
    nextActivity: "Read My Mind",
    startTime: "10:45",
  },
  {
    district: 5,
    subOG: 1,
    currentTR: "TR3",
    nextTR: "TR2",
    nextActivity: "Dizzy Directions",
    startTime: "11:15",
  },
  {
    district: 5,
    subOG: 1,
    currentTR: "TR2",
    nextTR: "None",
    nextActivity: "Eyes Wide Shut",
    startTime: "11:45",
  },
  {
    district: 6,
    subOG: 1,
    currentTR: "TR6",
    nextTR: "TR5",
    nextActivity: "The Irrelevant Answer",
    startTime: "10:15",
  },
  {
    district: 6,
    subOG: 1,
    currentTR: "TR5",
    nextTR: "TR4",
    nextActivity: "Stack and Steady",
    startTime: "10:45",
  },
  {
    district: 6,
    subOG: 1,
    currentTR: "TR4",
    nextTR: "TR3",
    nextActivity: "Read My Mind",
    startTime: "11:15",
  },
  {
    district: 6,
    subOG: 1,
    currentTR: "TR3",
    nextTR: "None",
    nextActivity: "Dizzy Directions",
    startTime: "11:45",
  },
  {
    district: 7,
    subOG: 1,
    currentTR: "TR7",
    nextTR: "TR6",
    nextActivity: "1 2 3 Don't Cheese",
    startTime: "10:15",
  },
  {
    district: 7,
    subOG: 1,
    currentTR: "TR6",
    nextTR: "TR5",
    nextActivity: "The Irrelevant Answer",
    startTime: "10:45",
  },
  {
    district: 7,
    subOG: 1,
    currentTR: "TR5",
    nextTR: "TR4",
    nextActivity: "Stack and Steady",
    startTime: "11:15",
  },
  {
    district: 7,
    subOG: 1,
    currentTR: "TR4",
    nextTR: "None",
    nextActivity: "Read My Mind",
    startTime: "11:45",
  },
  {
    district: 8,
    subOG: 1,
    currentTR: "TR8",
    nextTR: "TR7",
    nextActivity: "Silent Cards",
    startTime: "10:15",
  },
  {
    district: 8,
    subOG: 1,
    currentTR: "TR7",
    nextTR: "TR6",
    nextActivity: "1 2 3 Don't Cheese",
    startTime: "10:45",
  },
  {
    district: 8,
    subOG: 1,
    currentTR: "TR6",
    nextTR: "TR5",
    nextActivity: "The Irrelevant Answer",
    startTime: "11:15",
  },
  {
    district: 8,
    subOG: 1,
    currentTR: "TR5",
    nextTR: "None",
    nextActivity: "Stack and Steady",
    startTime: "11:45",
  },
  {
    district: 9,
    subOG: 1,
    currentTR: "TR1",
    nextTR: "TR8",
    nextActivity: "Read My Mind",
    startTime: "10:15",
  },
  {
    district: 9,
    subOG: 1,
    currentTR: "TR8",
    nextTR: "TR7",
    nextActivity: "Silent Cards",
    startTime: "10:45",
  },
  {
    district: 9,
    subOG: 1,
    currentTR: "TR7",
    nextTR: "TR6",
    nextActivity: "1 2 3 Don't Cheese",
    startTime: "11:15",
  },
  {
    district: 9,
    subOG: 1,
    currentTR: "TR6",
    nextTR: "None",
    nextActivity: "The Irrelevant Answer",
    startTime: "11:45",
  },
  {
    district: 10,
    subOG: 1,
    currentTR: "ARC - TR2",
    nextTR: "ARC - TR1",
    nextActivity: "Balloon Tower Build",
    startTime: "10:15",
  },
  {
    district: 10,
    subOG: 1,
    currentTR: "ARC - TR1",
    nextTR: "TR8",
    nextActivity: "Read My Mind",
    startTime: "10:45",
  },
  {
    district: 10,
    subOG: 1,
    currentTR: "TR8",
    nextTR: "TR7",
    nextActivity: "Silent Cards",
    startTime: "11:15",
  },
  {
    district: 10,
    subOG: 1,
    currentTR: "TR7",
    nextTR: "None",
    nextActivity: "1 2 3 Don't Cheese",
    startTime: "11:45",
  },
  {
    district: 11,
    subOG: 1,
    currentTR: "ARC - TR6",
    nextTR: "ARC - TR2",
    nextActivity: "Tic Tac Toe",
    startTime: "10:15",
  },
  {
    district: 11,
    subOG: 1,
    currentTR: "ARC - TR2",
    nextTR: "ARC - TR1",
    nextActivity: "Balloon Tower Build",
    startTime: "10:45",
  },
  {
    district: 11,
    subOG: 1,
    currentTR: "ARC - TR1",
    nextTR: "TR8",
    nextActivity: "Read My Mind",
    startTime: "11:15",
  },
  {
    district: 11,
    subOG: 1,
    currentTR: "ARC - TR8",
    nextTR: "None",
    nextActivity: "Silent Cards",
    startTime: "11:45",
  },
  {
    district: 12,
    subOG: 1,
    currentTR: "ARC - TR9",
    nextTR: "ARC - TR6",
    nextActivity: "Borderlight Battle",
    startTime: "10:15",
  },
  {
    district: 12,
    subOG: 1,
    currentTR: "ARC - TR6",
    nextTR: "ARC - TR2",
    nextActivity: "Tic Tac Toe",
    startTime: "10:45",
  },
  {
    district: 12,
    subOG: 1,
    currentTR: "ARC - TR2",
    nextTR: "ARC - TR1",
    nextActivity: "Balloon Tower Build",
    startTime: "11:15",
  },
  {
    district: 12,
    subOG: 1,
    currentTR: "ARC - TR1",
    nextTR: "None",
    nextActivity: "Read My Mind",
    startTime: "11:45",
  },
  {
    district: 13,
    subOG: 1,
    currentTR: "ARC - TR10",
    nextTR: "ARC - TR9",
    nextActivity: "The Irrelevant Answer",
    startTime: "10:15",
  },
  {
    district: 13,
    subOG: 1,
    currentTR: "ARC - TR9",
    nextTR: "ARC - TR6",
    nextActivity: "Borderlight Battle",
    startTime: "10:45",
  },
  {
    district: 13,
    subOG: 1,
    currentTR: "ARC - TR6",
    nextTR: "ARC - TR2",
    nextActivity: "Tic Tac Toe",
    startTime: "11:15",
  },
  {
    district: 13,
    subOG: 1,
    currentTR: "ARC - TR2",
    nextTR: "None",
    nextActivity: "Balloon Tower Build",
    startTime: "11:45",
  },
];

export const day2Activities: OGActivity[] = [
  {
    district: 1,
    subOG: 1,
    currentTR: "Outside Lt1",
    nextTR: "AIA Canopy",
    nextActivity: "Poker Run Station 1",
    startTime: "14:00",
  },
  {
    district: 1,
    subOG: 1,
    currentTR: "AIA Canopy",
    nextTR: "None",
    nextActivity: "Flag Capture Station 1",
    startTime: "15:00",
  },
  {
    district: 2,
    subOG: 1,
    currentTR: "Outside Lt1",
    nextTR: "AIA Canopy",
    nextActivity: "Poker Run Station 1",
    startTime: "14:00",
  },
  {
    district: 2,
    subOG: 1,
    currentTR: "AIA Canopy",
    nextTR: "None",
    nextActivity: "Flag Capture Station 1",
    startTime: "15:00",
  },
  {
    district: 3,
    subOG: 1,
    currentTR: "Outside TCT",
    nextTR: "Outside CEE Lvl 1",
    nextActivity: "Poker Run Station 2",
    startTime: "14:00",
  },
  {
    district: 3,
    subOG: 1,
    currentTR: "Outside CEE Lvl 1",
    nextTR: "None",
    nextActivity: "Relay race 1",
    startTime: "15:00",
  },
  {
    district: 4,
    subOG: 1,
    currentTR: "Outside TCT",
    nextTR: "Outside CCDS Lvl 1",
    nextActivity: "Poker Run Station 2",
    startTime: "14:00",
  },
  {
    district: 4,
    subOG: 1,
    currentTR: "Outside CCDS Lvl 1",
    nextTR: "None",
    nextActivity: "Flag Capture Station 2",
    startTime: "15:00",
  },
  {
    district: 5,
    subOG: 1,
    currentTR: "AIA Canopy",
    nextTR: "Outside CEE Lvl 1",
    nextActivity: "Flag Capture Station 1",
    startTime: "14:00",
  },
  {
    district: 5,
    subOG: 1,
    currentTR: "Outside CEE Lvl 1",
    nextTR: "None",
    nextActivity: "Relay race 1",
    startTime: "15:00",
  },
  {
    district: 6,
    subOG: 1,
    currentTR: "AIA Canopy",
    nextTR: "Outside CEE Lvl 1",
    nextActivity: "Flag Capture Station 1",
    startTime: "14:00",
  },
  {
    district: 6,
    subOG: 1,
    currentTR: "Outside CEE Lvl 1",
    nextTR: "None",
    nextActivity: "Relay race 1",
    startTime: "15:00",
  },
  {
    district: 7,
    subOG: 1,
    currentTR: "Outside CCDS Lvl 1",
    nextTR: "Nanyang Audi Lvl B1",
    nextActivity: "Flag Capture Station 2",
    startTime: "14:00",
  },
  {
    district: 7,
    subOG: 1,
    currentTR: "Nanyang Audi Lvl B1",
    nextTR: "None",
    nextActivity: "Relay Race Station 2",
    startTime: "15:00",
  },
  {
    district: 8,
    subOG: 1,
    currentTR: "Outside CCDS Lvl 1",
    nextTR: "Nanyang Audi Lvl B1",
    nextActivity: "Flag Capture Station 2",
    startTime: "14:00",
  },
  {
    district: 8,
    subOG: 1,
    currentTR: "Nanyang Audi Lvl B1",
    nextTR: "None",
    nextActivity: "Relay Race Station 2",
    startTime: "15:00",
  },
  {
    district: 9,
    subOG: 1,
    currentTR: "Outside CEE Lvl 1",
    nextTR: "Outside CCDS Lvl 1",
    nextActivity: "Relay Race Station 1",
    startTime: "14:00",
  },
  {
    district: 9,
    subOG: 1,
    currentTR: "Outside CCDS Lvl 1",
    nextTR: "None",
    nextActivity: "Flag Capture Station 2",
    startTime: "15:00",
  },
  {
    district: 10,
    subOG: 1,
    currentTR: "Outside CEE Lvl 1",
    nextTR: "Outside Lt1",
    nextActivity: "Relay Race Station 1",
    startTime: "14:00",
  },
  {
    district: 10,
    subOG: 1,
    currentTR: "Outside Lt1",
    nextTR: "None",
    nextActivity: "Poker Run Station 1",
    startTime: "15:00",
  },
  {
    district: 11,
    subOG: 1,
    currentTR: "Nanyang Audi Lvl B1",
    nextTR: "Outside Lt1",
    nextActivity: "Relay Race Station 2",
    startTime: "14:00",
  },
  {
    district: 11,
    subOG: 1,
    currentTR: "Outside Lt1",
    nextTR: "None",
    nextActivity: "Poker Run Station 1",
    startTime: "15:00",
  },
  {
    district: 12,
    subOG: 1,
    currentTR: "Nanyang Audi Lvl B1",
    nextTR: "Outside TCT",
    nextActivity: "Relay Race Station 2",
    startTime: "14:00",
  },
  {
    district: 12,
    subOG: 1,
    currentTR: "Outside TCT",
    nextTR: "None",
    nextActivity: "Poker Run Station 2",
    startTime: "15:00",
  },
  {
    district: 13,
    subOG: 1,
    currentTR: "Nanyang Audi Lvl B1",
    nextTR: "Outside TCT",
    nextActivity: "Relay Race Station 2",
    startTime: "14:00",
  },
  {
    district: 13,
    subOG: 1,
    currentTR: "Outside TCT",
    nextTR: "None",
    nextActivity: "Poker Run Station 2",
    startTime: "15:00",
  },
];
